package com.o0u0o.dianping.model;

public class CategoryModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cid
     *
     * @mbg.generated Sun Mar 08 19:26:33 CST 2020
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cname
     *
     * @mbg.generated Sun Mar 08 19:26:33 CST 2020
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cdesc
     *
     * @mbg.generated Sun Mar 08 19:26:33 CST 2020
     */
    private String cdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cid
     *
     * @return the value of category.cid
     *
     * @mbg.generated Sun Mar 08 19:26:33 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cid
     *
     * @param cid the value for category.cid
     *
     * @mbg.generated Sun Mar 08 19:26:33 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cname
     *
     * @return the value of category.cname
     *
     * @mbg.generated Sun Mar 08 19:26:33 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cname
     *
     * @param cname the value for category.cname
     *
     * @mbg.generated Sun Mar 08 19:26:33 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cdesc
     *
     * @return the value of category.cdesc
     *
     * @mbg.generated Sun Mar 08 19:26:33 CST 2020
     */
    public String getCdesc() {
        return cdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cdesc
     *
     * @param cdesc the value for category.cdesc
     *
     * @mbg.generated Sun Mar 08 19:26:33 CST 2020
     */
    public void setCdesc(String cdesc) {
        this.cdesc = cdesc == null ? null : cdesc.trim();
    }
}